# Generated by Django 4.2.6 on 2023-11-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.role')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.user')),
            ],
            options={
                'db_table': 'user_role',
                'ordering': ['user_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='modulerole',
            options={'ordering': ['module_id']},
        ),
        migrations.AlterModelOptions(
            name='viewmodule',
            options={'ordering': ['view_id']},
        ),
        migrations.RemoveField(
            model_name='modulerole',
            name='module',
        ),
        migrations.RemoveField(
            model_name='modulerole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='viewmodule',
            name='module',
        ),
        migrations.RemoveField(
            model_name='viewmodule',
            name='view',
        ),
        migrations.AddField(
            model_name='modulerole',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.module'),
        ),
        migrations.AddField(
            model_name='modulerole',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.role'),
        ),
        migrations.AddField(
            model_name='viewmodule',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.module'),
        ),
        migrations.AddField(
            model_name='viewmodule',
            name='view_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.view'),
        ),
        migrations.DeleteModel(
            name='PersonUser',
        ),
    ]
