# Generated by Django 4.2.6 on 2023-11-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_userrole_alter_modulerole_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='person',
            new_name='person_id',
        ),
    ]
