# Generated by Django 4.2.6 on 2023-11-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_rename_person_user_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='person_id',
            new_name='person',
        ),
    ]
