# Generated by Django 4.2.6 on 2023-11-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_rename_person_id_user_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulerole',
            options={'ordering': ['module']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='viewmodule',
            options={'ordering': ['view']},
        ),
        migrations.RenameField(
            model_name='modulerole',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='modulerole',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='viewmodule',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='viewmodule',
            old_name='view_id',
            new_name='view',
        ),
    ]
