# Generated by Django 4.2.6 on 2023-11-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_modulerole_options_alter_userrole_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='route',
            field=models.CharField(default='route', max_length=50),
        ),
        migrations.AddField(
            model_name='view',
            name='route',
            field=models.CharField(default='route', max_length=50),
        ),
    ]
